"""
SQLAlchemy DeclarativeBase with shared UUID PK and timestamp mixins.

All ORM models in ClinicOS Voice inherit from:
  Base (DeclarativeBase) + UUIDMixin + TimestampMixin
"""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Shared declarative base — imported in alembic/env.py for autogenerate."""
    pass


class UUIDMixin:
    """Provides a server-generated UUID v4 primary key column (`id`)."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
        comment="UUID v4 primary key — generated by the application layer.",
    )


class TimestampMixin:
    """
    Provides `created_at` and `updated_at` columns with automatic DB-side timestamps.
    `updated_at` is refreshed on every UPDATE via `onupdate`.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
