# initial_schema

"""initial_schema

Revision ID: 1c6a8b35d136
Revises: 
Create Date: 2026-06-17 17:48:02.766665+05:30
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c6a8b35d136'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v4 primary key — generated by the application layer.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eval_runs',
    sa.Column('run_name', sa.String(length=255), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=False, comment='Name of the dataset file used (e.g. booking_cases.json).'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Aggregate metrics: task_success_rate, hallucination_count, etc.'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v4 primary key — generated by the application layer.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='Primary lookup key used by the voice agent.'),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True, comment='Internal clinical notes — not exposed to the voice agent.'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v4 primary key — generated by the application layer.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_phone_number'), 'patients', ['phone_number'], unique=True)
    op.create_table('call_sessions',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('patient_phone', sa.String(length=20), nullable=True, comment="Caller's phone number — may be unknown at session start."),
    sa.Column('livekit_room_name', sa.String(length=255), nullable=True),
    sa.Column('agent_provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', 'FAILED', 'ABANDONED', name='call_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True, comment='LLM-generated or rule-based summary of the call outcome.'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v4 primary key — generated by the application layer.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_sessions_clinic_id'), 'call_sessions', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_call_sessions_patient_phone'), 'call_sessions', ['patient_phone'], unique=False)
    op.create_index(op.f('ix_call_sessions_status'), 'call_sessions', ['status'], unique=False)
    op.create_table('departments',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v4 primary key — generated by the application layer.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_clinic_id'), 'departments', ['clinic_id'], unique=False)
    op.create_table('eval_cases',
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('case_id', sa.String(length=100), nullable=False, comment='Human-readable case identifier.'),
    sa.Column('case_type', sa.String(length=50), nullable=False, comment='booking | rescheduling | cancellation | conflict | recovery'),
    sa.Column('input_scenario', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='The test case definition from the dataset.'),
    sa.Column('expected_outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actual_outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score', sa.String(length=20), nullable=True, comment='pass | partial | fail'),
    sa.Column('turns_taken', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('hallucination_detected', sa.Boolean(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v4 primary key — generated by the application layer.'),
    sa.ForeignKeyConstraint(['run_id'], ['eval_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_cases_case_type'), 'eval_cases', ['case_type'], unique=False)
    op.create_index(op.f('ix_eval_cases_run_id'), 'eval_cases', ['run_id'], unique=False)
    op.create_table('call_events',
    sa.Column('call_session_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Structured payload — contents vary by event_type.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Event timestamp — always UTC.'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v4 primary key — generated by the application layer.'),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_events_call_session_id'), 'call_events', ['call_session_id'], unique=False)
    op.create_index(op.f('ix_call_events_event_type'), 'call_events', ['event_type'], unique=False)
    op.create_table('doctors',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('qualification', sa.Text(), nullable=True),
    sa.Column('specialization', sa.Text(), nullable=True),
    sa.Column('consultation_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v4 primary key — generated by the application layer.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_clinic_id'), 'doctors', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_doctors_department_id'), 'doctors', ['department_id'], unique=False)
    op.create_table('doctor_slots',
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slot_status', sa.Enum('AVAILABLE', 'HELD', 'BOOKED', 'BLOCKED', name='slot_status_enum'), nullable=False),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when the HELD status expires and slot reverts to AVAILABLE.'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v4 primary key — generated by the application layer.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_slots_clinic_id'), 'doctor_slots', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_doctor_slots_doctor_id'), 'doctor_slots', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_slots_slot_status'), 'doctor_slots', ['slot_status'], unique=False)
    op.create_index(op.f('ix_doctor_slots_start_time'), 'doctor_slots', ['start_time'], unique=False)
    op.create_table('weekly_schedules',
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False, comment='0=Monday, 6=Sunday'),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v4 primary key — generated by the application layer.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_schedules_doctor_id'), 'weekly_schedules', ['doctor_id'], unique=False)
    op.create_table('appointments',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('appointment_type', sa.String(length=100), nullable=False, comment='new_consultation | follow_up | review | emergency'),
    sa.Column('status', sa.Enum('BOOKED', 'RESCHEDULED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', name='appointment_status_enum'), nullable=False),
    sa.Column('booking_source', sa.Enum('VOICE_AGENT', 'MANUAL', 'WEB', 'ADMIN', name='booking_source_enum'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rescheduled_from_appointment_id', sa.UUID(), nullable=True, comment='Pointer to the original appointment that was rescheduled into this one.'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID v4 primary key — generated by the application layer.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rescheduled_from_appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['slot_id'], ['doctor_slots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id')
    )
    op.create_index(op.f('ix_appointments_clinic_id'), 'appointments', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_clinic_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_weekly_schedules_doctor_id'), table_name='weekly_schedules')
    op.drop_table('weekly_schedules')
    op.drop_index(op.f('ix_doctor_slots_start_time'), table_name='doctor_slots')
    op.drop_index(op.f('ix_doctor_slots_slot_status'), table_name='doctor_slots')
    op.drop_index(op.f('ix_doctor_slots_doctor_id'), table_name='doctor_slots')
    op.drop_index(op.f('ix_doctor_slots_clinic_id'), table_name='doctor_slots')
    op.drop_table('doctor_slots')
    op.drop_index(op.f('ix_doctors_department_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_clinic_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_call_events_event_type'), table_name='call_events')
    op.drop_index(op.f('ix_call_events_call_session_id'), table_name='call_events')
    op.drop_table('call_events')
    op.drop_index(op.f('ix_eval_cases_run_id'), table_name='eval_cases')
    op.drop_index(op.f('ix_eval_cases_case_type'), table_name='eval_cases')
    op.drop_table('eval_cases')
    op.drop_index(op.f('ix_departments_clinic_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_call_sessions_status'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_patient_phone'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_clinic_id'), table_name='call_sessions')
    op.drop_table('call_sessions')
    op.drop_index(op.f('ix_patients_phone_number'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('eval_runs')
    op.drop_table('clinics')
    # ### end Alembic commands ###
